backend:
  name: git-gateway
  repo: aeckard87/addisonremote # change this to your repo
  branch: master
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "Lessons"
    label: "Lessons"
    label_singular: "Lessons"
    folder: "content/lessons"
    create: true
    slug: "{{slug}}"
    delete: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true}
      - { label: "Body", name: "body", widget: "markdown" }
